# settings config for Interactions

use_seed = false
random_seed = 1234
processes = 1

timeout = 3600
timeout_exit_code = 0 #0 to not exit?
capture_interval = 0 #how often (in terms of periods) to capture simulation state data

figure_dirpath = "" #defined which directory figures should be created in (if relative, relative to project root) #NOTE: could have one of these per database?

# sqlite database is provided by default
[databases]
# use = true
selected = "" #"sqlite.default"
attached = []
full_store = true #set to false to save partial information for storage efficiency. If false, simulations stored in the database will not be reproducable/continuable
# data_script = "" #supply to initialize database with specific data

[databases.sqlite.default]
path = "Interactions.sqlite"

# [databases.sqlite.checkpoint]
# path = "checkpoint.sqlite"

# add more sqlite databases below. For example:
# [databases.sqlite.my_sqlite_db]
# path = "my/sqlite/database/path.sqlite"


# postgres database must be configured by the user
# [databases.postgres.my_postgres_db]

# configure your own postgres databases below. For example:
# [databases.postgres.my_postgres_db]